[package]
name = "chip-8-rs"
version = "0.1.0"
authors = ["jmurray"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ggez = "0.5.1"
mint = "0.5.6"

rand = "0.8.3"

